use_frameworks!

platform :ios, '10.0'
target 'PickerEditImage_Example' do
  pod 'PickerEditImage', :path => '../'
  pod 'CropViewController'
  target 'PickerEditImage_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

